### ISSUE TITLE
v1 is not included latest features as README

### ISSUE THREAD

**Issue by tyankatsu0105** [actions/ai-inference#17]
# What
I tried to access the `response-file` in outputs as described in the documentation, but it doesn't exist.

```yml
- name: Test Local Action
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi cupiditate numquam non nulla nobis maiores commodi voluptatibus incidunt, dolores eligendi deleniti enim hic tempora provident quae consequuntur quia impedit ipsa!

- name: Use Response File
        id: response
        run: |
          echo "Response saved to: ${{ toJSON(steps.inference.outputs) }}"

# {
#  response: output text
# }
```

# Why

https://github.com/actions/ai-inference/releases/tag/v1.0.0 is not included latest codes.
