### ISSUE TITLE
[Feature]: Support for .prompt.yml files

### ISSUE THREAD

**Issue by FidelusAleksander** [actions/ai-inference#34]
Would it make sense for this action to support GitHub Models [.prompt.yml](https://docs.github.com/en/github-models/use-github-models/storing-prompts-in-github-repositories#supported-file-format) files? 

I'm imagining the interface could be like:

```yml
steps:
  - name: Run AI Inference
    id: inference
    uses: actions/ai-inference@v1
    with:
      prompt-file: './.github/prompts/sample.prompt.yml'
      input: |
         var1: hello
         var2: ${{ steps.<some-step>.outputs.<output> }}
         var3: |
           Lorem Ipsum
           Hello World

```

Or maybe you can think of something better, non-breaking that would support the prompt files
